### ISSUE TITLE
is there a way to pass additional parameter to ec2 instance, like enable detail monitor?

### ISSUE THREAD

**Issue by yangcheng** [machulav/ec2-github-runner#144]
cli would be like 
```aws ec2 run-instances --image-id ami-09092360 --monitoring Enabled=true...```

how to pass monitor parameter to the runner? 

thanks

**Comment by marcomancusooutra** [comment]
It does not look possible: https://github.com/machulav/ec2-github-runner/blob/fcfb31a5760dad1314a64a0e172b78ec6fc8a17e/src/aws.js#L35

**Comment by Preen** [comment]
Im closing this, if the prerequisites have changed since the issue was created, please create a new issue.
