### ISSUE TITLE
Github Runner - not able to register itself in GitHub as a new self-hosted runner

### ISSUE THREAD

**Issue by kemalgoekhan** [machulav/ec2-github-runner#153]
Hey everybody,

I would like to use self-hosted ec2 as you do :) 

The problem is should I add runner to github that created AMI in order to use or should not I add as self hosted runner on github before I created AMI?

I actually did both of them, and I am sure the sg is also okay but I can get ' A timeout of 5 minutes is exceeded. Your AWS EC2 instance was not able to register itself in GitHub as a new self-hosted runner.' 

Any idea to troubleshoot? Thanks in advance.

**Comment by Flyingliuhub** [comment]
Get the same issue for `A timeout of 5 minutes is exceeded. Your AWS EC2 instance was not able to register itself in GitHub as a new self-hosted runner.`
