### ISSUE TITLE
Unable to register self-hosted runner

### ISSUE THREAD

**Issue by danielMCF99** [machulav/ec2-github-runner#178]
I am trying to use this github action but I keep getting an error when checking if the GitHub self-hosted runner is registered.

Can anyone outline some possible reasons for this?

**Comment by GoLoTrust** [comment]
Same situation here =..(

**Comment by GoLoTrust** [comment]
Hey @danielMCF99 , Thanks for pointing this out! After some testing I tried by using our own AMI image where basically we use Ubuntu 22.04 and dependencies needed. Hope this can fix the problem for your use case though!!

**Comment by dysfunctor** [comment]
I ran into this because I did not do step 3.2 of the README: "Connect to the instance using SSH, install docker and git, then enable docker service."

Hope that helps!

**Comment by yambottle** [comment]
Folks, I ran into the same issue, and by default, the subnet I'm using sets `Auto-assign public IPv4 address` to `No`... It works when I set it to `Yes`

**Comment by AndriiPidiablonskyi** [comment]
Might be related to unsupported OS or arch, e.g. Github doesn't support Amazon Linux AMI for self-hosted runners, please refer [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners) for more details.

**Comment by 4cm3** [comment]
> Folks, I ran into the same issue, and by default, the subnet I'm using sets `Auto-assign public IPv4 address` to `No`... It works when I set it to `Yes`

This is the solution

**Comment by 4cm3** [comment]
> Might be related to unsupported OS or arch, e.g. Github doesn't support Amazon Linux AMI for self-hosted runners, please refer [here](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners) for more details.

I'm using Amazon Linux for self hosted runners and they work as expected. Will update if I find any issue

**Comment by roshkhatri** [comment]
Ran into the same issue 
>Folks, I ran into the same issue, and by default, the subnet I'm using sets Auto-assign public IPv4 address to No... It works when I set it to Yes

Worked after following this

Should probably be added to the README or have a TROUBLESHOOTING.md file

**Comment by TerenceTian625** [comment]
I set it to No, and the failed to register as self-hosted runner issue never appears, weird

**Comment by stecullum** [comment]
I had to make sure the image has "libicu"

For amazon Linux AL2003 I had to add...

```
        "sudo yum update -y",
        "sudo yum install docker libicu -y",  << important
        "sudo systemctl enable docker",
        "sudo systemctl start docker",

        "# Install docker compose plugin",
        "sudo curl -L \"https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-$(uname -m)\" -o /usr/libexec/docker/cli-plugins/docker-compose",
        "sudo chmod +x /usr/libexec/docker/cli-plugins/docker-compose"
     ```

**Comment by Preen** [comment]
Havent been able to confirm this yet in regards of AL2023. However until I have use Amazon Linux 2 for now. I will close this for now and if you encounter any new issues with runners not registering, create a new issue.
