### ISSUE TITLE
Support node 20

### ISSUE THREAD

**Issue by rogerdeulofeu** [machulav/ec2-github-runner#181]
As of today I'm receiving the following deprecation warning for this action
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: machulav/ec2-github-runner@v2.

**Comment by saadansari93** [comment]
+1

**Comment by carlosrandall** [comment]
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
