### ISSUE TITLE
add key name input for be able to connect to to ec2 instance 

### ISSUE THREAD

**Issue by lielran** [machulav/ec2-github-runner#22]

**Comment by machulav** [comment]
Hey @lielran! Can you please explain the use case for that? As you can always start the EC2 instance from your AMI manually with a key pair and debug it if needed.

**Comment by lielran** [comment]
yes, but it would be nice that you can connect to the instances that the ec2-github-runner is creating automatically

**Comment by machulav** [comment]
AWS recently introduced [EC2 Serial Console](https://aws.amazon.com/about-aws/whats-new/2021/03/introducing-ec2-serial-console/) - a new way of connecting to the instance even if it doesn't have a Key Pair configured.

To connect to the instance, make sure you configured the user with a password on the image beforehand.

Earlier I also thought it would be nice to configure the Kay Pair on the EC2 runner for debugging purposes. But this new way totally resolves the issue.
