### ISSUE TITLE
delete runners option as part of the teamdown

### ISSUE THREAD

**Issue by lielran** [machulav/ec2-github-runner#23]
it seems that the action isn't deleting those runners (as Github recommended).
I had to delete each one of them manually. 

![Screen Shot 2021-01-17 at 16 08 10](https://user-images.githubusercontent.com/1004667/104846640-3468c000-58e4-11eb-98fa-9135d9dce404.png)

**Comment by machulav** [comment]
@lielran can you please provide more details how you use the action in your workflow? The workflow code would be very helpful.

**Comment by hajapy** [comment]
I have seen this issue as well, and I am using the delete action with the if: always() trick. Going over the logs, I found a few cases where the runner teardown failed with a message saying the runner was still busy and could not be removed. I suppose there may be times where it takes longer for the state to change from busy to idle. We may wish to do a few retries in this case.
