### ISSUE TITLE
Not exiting when runner creation errors out

### ISSUE THREAD

**Issue by hajapy** [machulav/ec2-github-runner#27]
I had been pushing frequently while iterating on a workflow and ran into an issue which I think is due to hitting the usage limit of 1000 api calls /hr /repo. 

![Screen Shot 2021-01-21 at 10 44 05 PM](https://user-images.githubusercontent.com/21218230/105443746-75d9d200-5c3a-11eb-876c-107d2a9868e6.png)

Notice in the image, that though the code reached the timeout, this error continued to repeat and the job didn't exit even after the 10 minute timeout (I manually canceled the workflow). The instance was up and running, but perhaps not in time. It did not ever succeed to register, so the limit must have been hit before it could try to register.

So, something is in the reject/exit stack is not quite working? Also, it seems likely that the interval used to check whether the runner is created should be increased or made configurable.

**Comment by hajapy** [comment]
Perhaps missing a `clearInterval(interval)` here: https://github.com/machulav/ec2-github-runner/blob/main/src/gh.js#L65

**Comment by machulav** [comment]
> Perhaps missing a `clearInterval(interval)`

Good catch! 👍
Thanks!

> It did not ever succeed to register, so the limit must have been hit before it could try to register.
> Also, it seems likely that the interval used to check whether the runner is created should be increased or made configurable.

Based on my tests, even the smallest and least powerful EC2 instance type `t2.nano` is created and registered within 3 minutes. 

If the runner is not registered in 3 minutes then, then most probably the issue is in the connection to the Internet or, as you said, in limitation of the GitHub API. However, I didn't face such a problem with GitHub API limits before.

That's why I would even reduce the timeout from 10 minutes to 5 minutes to decrease the billable time when the EC2 instance registration is failed.

**Comment by hajapy** [comment]
Thanks for the fix. In my case I'm fairly confident the instance was able to connect to the internet (I've had many successful runners). I believe the polling rate is too high. At 60 api calls/minute, not accounting for any other api calls, we can only have about 16 minutes of waiting per hour per repo before reaching the rate limit. 

I was thinking to drop it to poll every 10s  and/or add a no-polling period for the first minute where it is very unlikely the runner will exist yet. This would help avoid unexpected issues for an active repo.

**Comment by machulav** [comment]
@hajapy It's actually a good point! I will try to measure the average time of the self-hosted runner registration and then add a timeout before start pulling every 10 seconds.
