### ISSUE TITLE
PR automation push to main?

### ISSUE THREAD

**Issue by hajapy** [machulav/ec2-github-runner#29]
Is this really intended? I don't think PRs should be pushing the dist on main. Perhaps back on the branch?

https://github.com/machulav/ec2-github-runner/blob/95f594d50902f20d08fa09af00a1aaf0c2cdded6/.github/workflows/pr.yml#L41

**Comment by machulav** [comment]
@hajapy Oh, you're right, I missed that. 🙈 
It shouldn't be like that. The commit should be pushing back on the branch.
Good that you noticed that! Thanks!
