### ISSUE TITLE
Error: A timeout of 5 minutes is exceeded. Please ensure your EC2 instance has access to the Internet.

### ISSUE THREAD

**Issue by mikemhenry** [machulav/ec2-github-runner#36]
I'm sure that this is a configuration issue on my end but I'm not sure what the problem is.

Link to my yml:
https://github.com/choderalab/super-duper-guacamole/blob/27b75e91103c5804e1d056908cb4c97110b5a7eb/.github/workflows/self-hosted-test.yml

Link to github action log:
https://github.com/choderalab/super-duper-guacamole/runs/2273873236?check_suite_focus=true

I made the inbound traffic rules wide open to help troubleshoot this:
```
Inbound rules
Type | Protocol | Port range | Source | Description - optional
-- | -- | -- | -- | --
All traffic | All | All | 0.0.0.0/0 | wide open for testing
All traffic | All | All | ::/0 | wide open for testing
```

```
Outbound rules
Port range | Protocol | Destination | Security groups
-- | -- | -- | --
443 | TCP | 0.0.0.0/0 | GitHubActionSelfHostedRunner
```
I'm able to SSH onto the EC2 instance that gets spun up -- any other ideas on how to test?

**Comment by machulav** [comment]
Hey @mikemhenry, thanks for your question!

The issue could be related to the type of EC2 instance you selected: `t4g.micro` is based on ARM64 CPU architecture, and the action currently uses x64 compatible GitHub Action Runner package as you can see here: https://github.com/machulav/ec2-github-runner/blob/main/src/aws.js#L13

As a result, I would expect that the runner is just can not be started on your EC2 instance and register itself in your GitHub repository. Try to use x64 compatible EC2 instance.

I hope it helps!

**Comment by mikemhenry** [comment]
I'm sure that is the issue! I am looking at this again today. Do you intend on supporting multiple architectures? Perhaps it defaults to x86 but could support arm64? It is a pre-release but I am interested in helping you test if needed.

**Comment by davinchia** [comment]
Hi, I'm running into this even on an intel based instance. This is my [yaml](https://github.com/airbytehq/airbyte/pull/2934/files#diff-4a8c5b012eea067353ad636305171589494e274fed61de7b23d4eaf111453b91R1).

My networking is also wide open for testing, both inbound and outbound. Any idea how one would go about debugging this?

**Comment by machulav** [comment]
Hey @davinchia,

> The instance is currently running in a private VPC/subnet with a private IP. Does the instance need a public IP?

If you run it in the private subnet, please make sure you use NAT Gateway with this subnet, so your instance with private IP has access to the Internet and can pull the jobs from GitHub. Otherwise, the instance with the private IP won't be able to connect to the internet.

I hope it helps!

**Comment by machulav** [comment]
> I'm sure that is the issue! I am looking at this again today.

I hope you resolve the issue!

> Do you intend on supporting multiple architectures? Perhaps it defaults to x86 but could support arm64?

Yeah, it's definitely a good point to support multiple architectures! Created a new issue for that #37 

> It is a pre-release but I am interested in helping you test if needed.
Cool, thanks a lot! I will notify you when it's ready for testing.

**Comment by davinchia** [comment]
> If you run it in the private subnet, please make sure you use NAT Gateway with this subnet, so your instance with private IP has access to the Internet and can pull the jobs from GitHub. Otherwise, the instance with the private IP won't be able to connect to the internet.

@machulav you were right - worked once I attached a NAT gateway!
