### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by machulav** [machulav/ec2-github-runner#37]
The issue is resolved in this fork: https://github.com/machulav/ec2-github-runner/compare/main...theopolis:main by @theopolis

**Comment by machulav** [comment]
Hey @mikemhenry! Just FYI: the ARM64 support enhancement is merged to the `main`. If you have some time, please double-check if it works in your case. Later I will create a new version with it.

**Comment by mikemhenry** [comment]
@machulav I can confirm it works! 
https://github.com/choderalab/super-duper-guacamole/pull/1/checks?check_run_id=2412600208
(ignore the error in the next step -- the ami I used is missing some software I need)

**Comment by machulav** [comment]
Awesome! Thank you for checking! 🙏
