### ISSUE TITLE
Runners not cleaned up from the list of GitHub runners

### ISSUE THREAD

**Issue by jduncan-xoi** [machulav/ec2-github-runner#42]
When using the standard ec2 runner setup from the documentation it seems as if the GitHub runners aren't being cleaned up. The returned message is `GitHub self-hosted runner with label <random id> is not found, so the removal is skipped` but when I look at the list of runners, I see the runner with that label as offline. The AWS side seems to clean up  properly. In any case, thanks for this great tool!

**Comment by jduncan-xoi** [comment]
eh, i discovered this was entirely me. sorry about that!

**Comment by machulav** [comment]
@jduncan-xoi Good that you found the root cause. Can you please share the reason behind that?

**Comment by jduncan-xoi** [comment]
> @jduncan-xoi Good that you found the root cause. Can you please share the reason behind that?

@machulav Sure, I had a bad token for the stop-runner section. I suppose one enhancement proposal could be to make the errors more verbose as when it has a bad token or null for the token, it just returns null and the message in the original post here.

**Comment by machulav** [comment]
It makes a lot of sense! Thanks for the notice!
