### ISSUE TITLE
Error: GitHub Registration Token receiving error Error: HttpError: Not Found Error: Not Found

### ISSUE THREAD

**Issue by M-JobPixel** [machulav/ec2-github-runner#48]
I have configured this runner for use but when it tries to run the start-runner job it exits with 

Error: GitHub Registration Token receiving error
Error: HttpError: Not Found
Error: Not Found

It seems to be falling over here: 
https://github.com/machulav/ec2-github-runner/blob/21b339b35e4ff193edd67181694ca4fabd7d481b/src/gh.js#L24-L32

so I guess that /repos/{owner}/{repo}/actions/runners/registration-token is the URL which is Not Found.

I've tried ensuring that my Access Token is correct and it seems to be.

I can't imagine that github would be blocking access to their own API from the runners.

Does anyone know what I've missed?

**Comment by M-JobPixel** [comment]
This turns out to be a permissions error.

I'm not quite sure what level of permissions are needed, by the user issuing the PAT, yet.

But I switched from using the PAT of my robots account to my personal account and I get the Token.

So the user issuing the PAT may need admin rights on the repo this runs in.

**Comment by M-JobPixel** [comment]
Just to confirm that giving the robot Admin rights to the repo made it's PAT work.

**Comment by myatsko-ledger** [comment]
Issue confirmed, I hit it too
Needing an Admin level token seems to be a bit weird though

**Comment by myatsko-ledger** [comment]
Issue confirmed, I hit it too
Needing an Admin level token seems to be a bit weird though

**Comment by matthewmucker-vizio** [comment]
According to the comments in the code, the script dynamically registers a self-hosted runner with Github. I think that may be the action that requires administrative access to the repo.

**Comment by riteshkumar-prive** [comment]
@M-JobPixel @myatsko-ledger @matthewmucker-vizio 
I have hit the same issue.
I have created the PAT token with `admin:org`, `repo`,`workflow` scope but still its not working.

Do I need to provide the user with Admin level repo access along with `repo` scope to the PAT?

**Comment by piyushdatazip** [comment]
@riteshkumar-prive I don't this works with ORGs right now, since new fine grained token has came up
