### ISSUE TITLE
Support for GCE/GCP runner

### ISSUE THREAD

**Issue by ravwojdyla** [machulav/ec2-github-runner#49]
👋  internally we have somewhat similar approach for a GCE/GCP self-hosted runner. We are considering open-sourcing it. Do you think it would be a good idea to make this action "cloud agnostic", and add support for GCE based self-hosted runner here, or would you suggest to make a separate action?

**Comment by hammer** [comment]
For those interested, this code is now open source: https://github.com/related-sciences/gce-github-runner.

**Comment by machulav** [comment]
@ravwojdyla @hammer Hey, thank you for the idea and open-sourcing your project. That's awesome!

When I started this project, I also considered making it cloud-agnostic as sooner or later, there definitely will be demand for such action for different clouds. However, then I decided to narrow the scope down to what I know the best and carved this approach in the name of the action :-) I believe that if the thing is simple, it's easier to maintain it and provide a better service.

Still, I really like your idea to make it available on GCP! If I can help you with something for the GCP action, please let me know - I would be happy to help.

**Comment by ravwojdyla** [comment]
Thanks @machulav! I appreciate your comment! In that case let's keep the GCE/GCP action in https://github.com/related-sciences/gce-github-runner for now. I believe we can close this issue? I have added a link to your action in our readme: https://github.com/related-sciences/gce-github-runner#ec2aws-action for people that might need EC2 self-hosted runners.

**Comment by machulav** [comment]
@ravwojdyla thank you! I'm closing this task.
