### ISSUE TITLE
How to assign public ip to ec2 instance

### ISSUE THREAD

**Issue by raghulkrishna** [machulav/ec2-github-runner#52]
How to assign public ip to ec2 instance

**Comment by danielloader** [comment]
This would be surprisingly helpful in some VPC situations. Can't always jam a NAT gateway in.

**Comment by jpalomaki** [comment]
As this action does not currently support associating a public IP on instance launch (see https://github.com/machulav/ec2-github-runner/blob/main/src/aws.js#L22-L32), you'd need to run the instance in a subnet that is configured for automatic public IP assignment.

See relevant [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#concepts-public-addresses) for more information.

**Comment by jpalomaki** [comment]
@machulav @danielloader Here's a quick stab at it: #57. Let me know what you think.
