### ISSUE TITLE
Assign IAM role to the EC2 instance

### ISSUE THREAD

**Issue by machulav** [machulav/ec2-github-runner#6]
# Notes
- it will potentially enable a new use case: "Access AWS resources using IAM policy and without using static IAM access keys"

**Comment by hajapy** [comment]
@machulav Thanks for sharing this action! I've been experimenting with it and thought I could chip in. https://github.com/machulav/ec2-github-runner/pull/25 is an attempt to resolve this issue and allow IAM roles to be passed in. I have tested a version of this and got it to work.

**Comment by machulav** [comment]
@hajapy thanks a lot for your support and contributions! 🙏 I'm really glad that you found this action helpful! I will take a look into the PR as soon as possible and let you know.

**Comment by machulav** [comment]
@hajapy Looks great and works as expected! Thanks again for your contribution!
