### ISSUE TITLE
Support multiple regions/availabilty zones if an instance type cannot be started

### ISSUE THREAD

**Issue by gilShin** [machulav/ec2-github-runner#60]
We are using instances types that require lots of reasources. Because of, from time to time it is impossible to start an instance of some type in a certain region and a certain AZ.
It'll be great if this plugin will be able to run over list of regions/AZs (subnets and security groups) and start the instance where its type is available.

**Comment by jpalomaki** [comment]
Turns out one can only omit subnet ID from run parameters, if you are using the default VPC.

> [EC2-VPC] If you don't specify a subnet ID, we choose a default subnet from your default VPC for you. If you don't have a default VPC, you must specify a subnet ID in the request. 

See [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html)

**Comment by gilShin** [comment]
If I do use the default vpc, will it try in one AZ or will keep on trying
in all AZs?
Anyhow I would like that to be across regions as well.

I did solve it using a very ugly workaround but seems like working. In the
start job, I have added a step that if it fails, it triggers the workflow
again with different subnet ID. The subnet is of the start step uses an env
variable that uses an input parameter.

**Comment by jpalomaki** [comment]
> If I do use the default vpc, will it try in one AZ or will keep on trying
in all AZs?

I don't know, but I suspect it would just pick one.

What I'd like to know is if the automatic selection algorithm is AZ capacity-aware.

**Comment by gilShin** [comment]
I doubt that and I'll explain why.
Capacity of what? Vcpu? Mem? GPU? You can have enough vcpus in a certain AZ
but no GPUs.
I think it just picks up a subnet randomly and hope for the best. For us it
is even worst because we are using mostly GPUs and not all AZs in a certain
region has that type that we are looking for.

**Comment by jpalomaki** [comment]
All needed capacity. AWS must be checking them anyhow, at instance launch time, to be able to distribute/optimize load.

Looking at https://aws.amazon.com/premiumsupport/knowledge-center/ec2-insufficient-capacity-errors/ and then https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshooting-launch.html#troubleshooting-launch-capacity, the latter link does mention "not specifying AZ" as one solution. :man_shrugging: 

That said, one option could be to abstract the runner start job in a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) that tries `ec2-github-runner` start with different region/AZ settings (in consecutive, conditional steps) until it succeeds, returning the start mode outputs from the successful step?

**Comment by gilShin** [comment]
Can be a solution but I think it'll be best if the code can go over list of
regions and AZs and try in each and every one of them.

I did something similar in Jenkins pipeline

**Comment by stas00** [comment]
And while we are at it, when it fails to start because of the region not having an instance I get a while bunch of errors on stopping:

![snapshot_14](https://user-images.githubusercontent.com/10676103/131441844-e3ea5887-afcc-4836-b479-809932455dbc.png)

**Comment by jpalomaki** [comment]
> And while we are at it, when it fails to start because of the region not having an instance I get a while bunch of errors on stopping

That can probably be fixed by amending the `if` condition on the stop job (to also check the result of the start job)

**Comment by jpalomaki** [comment]
@stas00 would something like this work? (NOTE: untested and some details omitted for brevity):
```
jobs:
  start-runner:
    runs-on: ubuntu-20.04
    outputs:
      label: ${{ steps.result.outputs.label }}
      ec2-instance-id: ${{ steps.result.outputs.ec2-instance-id }}
    steps:
      ...
      - id: try-us-east-2a
        uses: machulav/ec2-github-runner@v2
        continue-on-error: true
        with:
          mode: start
          subnet-id: subnet-on-2a
          ...
      - id: try-us-east-2b
        if: steps.try-us-east-2a.outcome == 'failure'
        uses: machulav/ec2-github-runner@v2
        continue-on-error: true
        with:
          mode: start
          subnet-id: subnet-on-2b
          ...
      - id: try-us-east-2c
        if: steps.try-us-east-2b.outcome == 'failure'
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          subnet-id: subnet-on-2c
          ...
      - id: result
        run: |
          if [ "${{ steps.try-us-east-2a.outcome }}" = "success" ]; then
            echo "::set-output name=label::${{ steps.try-us-east-2a.outputs.label }}"
            echo "::set-output name=ec2-instance-id::${{ steps.try-us-east-2a.outputs.ec2-instance-id }}"
          fi
          if [ "${{ steps.try-us-east-2b.outcome }}" = "success" ]; then
            echo "::set-output name=label::${{ steps.try-us-east-2b.outputs.label }}"
            echo "::set-output name=ec2-instance-id::${{ steps.try-us-east-2b.outputs.ec2-instance-id }}"
          fi
          if [ "${{ steps.try-us-east-2c.outcome }}" = "success" ]; then
            echo "::set-output name=label::${{ steps.try-us-east-2c.outputs.label }}"
            echo "::set-output name=ec2-instance-id::${{ steps.try-us-east-2c.outputs.ec2-instance-id }}"
          fi
```
Also, if we supported launch templates (see #65), then multi-region would be less awkward as we could have a template per region (also less inputs per `ec2-github-runner` step)?

**Comment by stas00** [comment]
Thank you for writing out a concrete example, @jpalomaki! I will try and report back.

So it's the same sub-region we are using the same AMI /security group, but only rotating though the subnet-ids. Got it.

**Comment by jpalomaki** [comment]
> Thank you for writing out a concrete example, @jpalomaki! I will try and report back.
> 
> So it's the same sub-region we are using the same AMI /security group, but only rotating though the subnet-ids. Got it.

Np.

NOTE: I now fixed the `if` condition on the `try-us-east-2c` step so that it only runs if _both_ previous steps failed. Also be sure to monitor how many instances/runners are actually spawned, to avoid excess costs.

**Comment by stas00** [comment]
So I have done quite a few experiments and your example works perfectly well, @jpalomaki - thank you so much.

I switched to us-east-1 since us-east-2 didn't even have 3 subnets that supported the instance type I needed. On us-east-1 I think there are only 3.

It'd be nice to be able to remove the repetition of `aws-resource-tags` and other sections if at all possible. If not, that's OK too.

The final config is here:

https://github.com/bigscience-workshop/Megatron-DeepSpeed/blob/9e14c02a1dd22e4d36e2ee9a33e44d33774b8de7/.github/workflows/main.yml#L17

**Comment by gilShin** [comment]
So is it going to support only different AZs but not different regions?

Thanks

**Comment by stas00** [comment]
this particular setup is just sub-regions.

I'm concerned this might not be enough still at times. So different regions would be even more fault tolerant, but this is already a great start.

**Comment by gilShin** [comment]
I agree that this is a good start but with the types we're using,
unfortunately, it won't be enough :-(

**Comment by machulav** [comment]
@stas00, great that you've made it to work!
@jpalomaki, thank you a lot for your help and examples! I really appreciate your help here!

I hope that the launch templates from #65 will make selecting the AZ from the region less painful in the future. Maybe it will be helpful also for the region selection when you have one launch template in each region and then try to create instances in each region one by one using the example from @jpalomaki.

But for now, I close the issue as we have a solution. Let's monitor the situation and re-open it if required.

**Comment by mgaitan** [comment]
Hey, I've implemented [the idea](https://github.com/machulav/ec2-github-runner/issues/60#issuecomment-906970881) of @philschmid

> We could make config.input.subnetId a list and try to iterate randomly over it

Check this
https://github.com/Shiphero/ec2-github-runner/commit/69a9f36c03902c200ca9a02a19e92487a149fecf
