### ISSUE TITLE
Runner software on running EC2 instance does not register with GitHub

### ISSUE THREAD

**Issue by mayormaier** [machulav/ec2-github-runner#61]
Hello, I'm having an issue with the "start" mode of this action, as the runner software on my EC2 instance does not register with GitHub. I have a feeling that this issue is caused by the instance's lack of internet connection as the action hangs at "Checking every 10 seconds to see if the runner is registered". 
![Screen Shot 2021-08-12 at 4 27 36 PM](https://user-images.githubusercontent.com/70287117/129265011-df8b1264-1dcb-4e0b-81a8-1a914982d4bf.png)
The instance is started and stopped correctly by the Action. This is my first application of this action in my work, so I have not implemented this action before.

I've taken the following steps so far:

The security group which is attached to the instance allows all outbound traffic
A NAT gateway was added to the VPC/Subnet containing the instance
The route table of the VPC/subnet points internet traffic to the NAT gateway
Regenerating the GitHub token used in this repository

Has anyone else encountered this issue, if so, how did you resolve it?

**Comment by jpalomaki** [comment]
@mayormaier You need to provision the NAT gateway in another (public) subnet, for which the Internet (0.0.0.0/0) route points to your VPC's Internet Gateway.

See https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html for more information.

**Comment by mayormaier** [comment]
I was able to fix the issue by following the recommended steps. Thank you.

**Comment by robertsonsamuel** [comment]
@jpalomaki I am also running into this issue, however I am able to boot an AMI with the Github Actions runner myself in an AMI instance, then boot that and see the github actions runner in the "Runners" portion of my repository. Is there something else I'm missing ?

**Comment by jpalomaki** [comment]
> @jpalomaki I am also running into this issue, however I am able to boot an AMI with the Github Actions runner myself in an AMI instance, then boot that and see the github actions runner in the "Runners" portion of my repository. Is there something else I'm missing ?

So a GitHub workflow fails to register the runner (timing out), but when running a similar instance manually, runner registration succeeds?

If so, did you use the _exact_ same settings (AMI, VPC, subnet, security group etc) when launching the instance manually?

**Comment by robertsonsamuel** [comment]
@jpalomaki yes! I was going to update this today! I figured out I wasn't attaching the correct security group, so requests for being blocked. A quick look at `/var/logs/syslog` in ubuntu server solved that pretty quick. Thanks so much for replying! Great work on this project too!
