### ISSUE TITLE
Are instances guaranteed to be terminated?

### ISSUE THREAD

**Issue by vroad** [machulav/ec2-github-runner#7]
What happens if a workflow is cancelled, or GitHub goes down?
The action only uses plain RunInstances call, so launched instances will never get terminated if the stop instance step fails to run?

Hashicorp packer has similar issues because it also uses RunInstances.

https://binx.io/blog/2020/03/27/how-to-terminate-packer-instances-on-aws/

**Comment by machulav** [comment]
@vroad, thank you for your feedback! That's a very good question!

> What happens if a workflow is canceled

The GitHub Actions syntax provides the possibility to run the job even if the previous jobs failed or the entire run was canceled. This is a guarantee that the runner termination job will always be run in such cases. See more details in PR #9.

> or GitHub goes down

> The action only uses plain RunInstances call, so launched instances will never get terminated if the stop instance step fails to run?

Yes, you're right. I have an idea to use "idle timeout" for issue #4. It should resolve this problem as well.

**Comment by machulav** [comment]
I close the issue as the biggest part of it, which is possible to fix in the current implementation, was fixed in PRs #7 and #10.
The rest will be covered in issue #4.

@vroad thank you for bringing up this topic!
