### ISSUE TITLE
Can't execute job on created EC2

### ISSUE THREAD

**Issue by afedotov-align** [machulav/ec2-github-runner#77]
Hi colleagues,

After instance creation job couldn't be run on EC2 machine. 
Instances could be created and terminated in my VPC, outbound traffic is allowed on port 443 with security group.
What can be the cause and where I should start troubleshooting?

Thanks, Artem.

```
AWS EC2 instance i-xxxxxxxx is up and running
Waiting 30s for the AWS EC2 instance to be registered in GitHub as a new self-hosted runner
Checking every 10s if the GitHub self-hosted runner is registered
Checking...
Checking...
Checking... (x N times)
Error: GitHub self-hosted runner registration error
Error: A timeout of 5 minutes is exceeded. Your AWS EC2 instance was not able to register itself in GitHub as a new self-hosted runner.
```

**Comment by afedotov-align** [comment]
Hello everyone,

I was finally managed to figure out the cause of the issue!

_./bin/installdependencies.sh_ must be run while preparing AMI for build

I used _centos-release-7-9.2009.1.el7.centos.x86_64_.

I suppose it could be mentioned in preparation steps, because it's not really obvious. Or this step could be added to steps for client installation.

Thanks, Artem.

**Comment by Shan-KulK** [comment]
Sorry to drag up and old issue, but what is in your `./bin/installdependencies.sh` and where/when did you run it? I'm getting the same error and prepared the custom AMI as shown in the steps. I assume you are referring to preparing the custom AMI? @afedotov-align any help would be appreciated as I really have been stuck on this for a while. Thanks for opening and closing the issue!

**Comment by ouraluukas** [comment]
@Shan-KulK a bit late but did you ever get it to work? Getting the same output as you.
